#!/usr/bin/env python3
"""Render the original semiology course from its reviewable, local data files."""
import html
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
SECTION=ROOT/'24_Semiologia'
MODULE=SECTION/'Cardiovascular'
def read(name): return json.loads((MODULE/'data'/f'{name}.json').read_text())
def e(value): return html.escape(str(value),quote=True)
data={key:read(key) for key in ('lessons','sounds','recordings','cases','sources','syndromes')}
data['audio']=read('audio-manifest')
data['version']='1.0.0'
data['flashcards']=[{'id':'lesson-'+x['id'],'question':x['question'],'answer':x['answer'],'lesson':x['id']} for x in data['lessons']]
data['flashcards'] += [{'id':'sound-'+x['id'],'question':f"{x['title']}: o que localizar no ciclo e o que evitar concluir?",'answer':x['listen']+' '+x['pitfall'],'sound':x['id']} for x in data['sounds']]
extra=[
 ('onda-a','O que produz a onda a jugular?','Contração atrial organizada; pode desaparecer na fibrilação atrial.'),
 ('onda-v','Por que a onda v/cv pode ser proeminente na insuficiência tricúspide?','A regurgitação sistólica aumenta o enchimento/pressão do átrio direito durante a sístole.'),
 ('carotidas','Qual cuidado essencial na palpação carotídea?','Palpação suave e unilateral. Nunca comprimir ambas as carótidas simultaneamente.'),
 ('levine','A partir de qual grau sistólico de Levine há frêmito?','IV/VI. Intensidade acústica não equivale sozinha à gravidade anatômica.'),
 ('austin-flint','Ruflar de Austin Flint confirma estenose mitral anatômica?','Não. Pode acompanhar insuficiência aórtica importante e precisa ser diferenciado por avaliação integrada e imagem.'),
 ('pocus','Por que POCUS não substitui automaticamente um estudo valvar completo?','É um exame focado, dependente de janela e operador; Doppler, quantificação e integração podem exigir estudo completo.'),
 ('ortho','Qual é a definição usual de hipotensão ortostática?','Queda sustentada ≥20 mmHg sistólica OU ≥10 mmHg diastólica em até 3 minutos ao levantar; interpretar contexto e segurança.'),
 ('kussmaul','Kussmaul é sinônimo de tamponamento?','Não. Falta de queda ou elevação inspiratória da jugular sugere limitação do enchimento direito, como constrição, restrição ou infarto de VD.')]
data['flashcards'] += [dict(id='extra-'+i,question=q,answer=a,lesson='pratica') for i,q,a in extra]
data['checklist']=[
 'Avaliar conforto, respiração, perfusão e sinais de instabilidade antes do roteiro completo.',
 'Obter consentimento, privacidade e posição tolerada.',
 'Definir sintoma principal, início, gatilhos e mudança funcional.',
 'Revisar sinais vitais, pressão com técnica apropriada e ritmo.',
 'Inspecionar mucosas, extremidades, edema e sinais sistêmicos relevantes.',
 'Descrever pulsos: frequência, regularidade, amplitude, contorno e simetria.',
 'Examinar carótida suavemente, um lado de cada vez, quando apropriado.',
 'Avaliar jugular, posição de exame, altura, ondas e variação respiratória.',
 'Palpar ictus: posição, extensão, amplitude e duração.',
 'Procurar impulso paraesternal e frêmitos, localizando-os no ciclo.',
 'Identificar B1 e B2 antes de nomear qualquer sopro.',
 'Ouvir base, borda esternal, ápice e áreas de irradiação.',
 'Usar campânula leve e posições adequadas para sons graves.',
 'Caracterizar sopro: tempo, forma, foco, irradiação, intensidade e timbre.',
 'Se seguro e útil, prever e observar resposta a uma manobra apropriada.',
 'Integrar sinais de congestão, perfusão, lesão valvar e pericárdio.',
 'Definir o que precisa de confirmação e a urgência; não atrasar suporte.',
 'Registrar uma descrição reproduzível e uma lacuna para estudo, sem dados pessoais neste site.'
]
data['tracks']=[
 {'title':'Primeira escuta · 5–8 min','steps':[['Localize B1 e B2','ciclo'],['Ouça normal e B3','laboratorio'],['Responda um caso e um flashcard','casos']]},
 {'title':'Sopros sistólicos · 12–15 min','steps':[['Revise como descrever o sopro','descrever-sopro'],['Compare aórtico, mitral e tricúspide','laboratorio'],['Preveja uma manobra antes de revelar','manobras-lab'],['Resolva casos com contexto','casos']]},
 {'title':'Diástole e pericárdio · 12–15 min','steps':[['Revise sons adicionais','sons-extras'],['Compare B3, estalido mitral, IA e atrito','laboratorio'],['Integre congestão e síndromes pericárdicas','sindromes-lab'],['Retome cartões difíceis','revisao']]},
 {'title':'Retorno após a prática · 5 min','steps':[['Confira a sequência de exame','checklist'],['Revise a lacuna observada','aprender'],['Faça treino auditivo sem rótulo','treino-auditivo'],['Salve ou exporte seu progresso','progresso']]}
]
sources={x['id']:x for x in data['sources']}
def refs(ids):return '<div class="source-links">'+''.join(f'<a href="{e(sources[i]["url"])}" target="_blank" rel="noopener">{e(sources[i]["title"])}</a>' for i in ids)+'</div>'
lessons=''
for lesson in data['lessons']:
 blocks=''.join(f'<div class="lesson-block"><h4>{e(x["title"])}</h4><p>{e(x["text"])}</p></div>' for x in lesson['blocks'])
 lessons+=f'''<article class="lesson" id="{e(lesson['id'])}"><h3>{e(lesson['title'])}</h3><p class="lead">{e(lesson['lead'])}</p><details class="lesson-details"><summary>Aprofundar este passo</summary>{blocks}{refs(lesson['sources'])}</details><div class="recall"><strong>Recupere sem olhar</strong><p>{e(lesson['question'])}</p><details><summary>Conferir resposta</summary><p>{e(lesson['answer'])}</p></details></div><label class="learn-check no-print"><input type="checkbox" data-lesson="{e(lesson['id'])}"> Revisei este passo e respondi à pergunta</label></article>'''
syndromes=''.join(f'''<details class="syndrome-card" id="syndrome-{e(x['id'])}"><summary>{e(x['title'])}</summary><ul>{''.join('<li>'+e(t)+'</li>' for t in x['findings'])}</ul><h4>Mecanismo</h4><p>{e(x['mechanism'])}</p><h4>Próxima pergunta clínica</h4><p>{e(x['next'])}</p><div class="note caution">{e(x['trap'])}</div>{refs(x['sources'])}</details>''' for x in data['syndromes'])
source_html=''.join(f'''<article class="source-entry"><a href="{e(x['url'])}" target="_blank" rel="noopener"><strong>{e(x['title'])}</strong></a><p>{e(x['scope'])}</p><small>{e(x['type'])} · consultada em 08/09/2026</small></article>''' for x in data['sources'])
def head(title,prefix):return f'''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#061220"><meta name="description" content="Semiologia AldenirMed89: exame clínico, ausculta, casos comentados e aprendizagem contínua."><meta http-equiv="Content-Security-Policy" content="default-src 'self'; img-src 'self' data: https://aldenirrochadeoliveirafilho1989.goatcounter.com; media-src 'self' blob:; style-src 'self'; script-src 'self' https://gc.zgo.at; connect-src 'self' https://aldenirrochadeoliveirafilho1989.goatcounter.com; object-src 'none'; base-uri 'self'; form-action 'none'"><title>{e(title)} · AldenirMed89</title><link rel="icon" href="{prefix}assets/icons/aerospace-v2/icon-32.png"><link rel="apple-touch-icon" href="{prefix}assets/icons/aerospace-v2/apple-touch-icon-180.png"><link rel="manifest" href="{prefix}manifest.webmanifest"><link rel="stylesheet" href="{'../' if prefix=='../../' else ''}assets/semio.css"><script src="{'../' if prefix=='../../' else ''}assets/theme.js"></script></head>'''
def bar(prefix,course=False):return f'''<a class="skip" href="#conteudo">Pular para o conteúdo</a><header class="sitebar"><a class="brand" href="{prefix}index.html"><img src="{prefix}assets/icons/aldenirmed89-aerospace-orbital-192.png" width="44" height="44" alt=""><span><strong>AldenirMed89</strong><small>SEMIOLOGIA · APRENDER COM A PRÁTICA</small></span></a><div class="bar-actions">{'<button id="menu-toggle" type="button" aria-expanded="false" aria-controls="course-nav">☰ Seções</button>' if course else ''}<button id="theme-toggle" type="button" aria-label="Ativar visualização clara" aria-pressed="false">☀ Claro</button></div></header>'''
hub=head('Semiologia','../')+f'''<body>{bar('../')}<main class="container" id="conteudo"><div class="hero"><p class="eyebrow">ESTAÇÃO DE SEMIOLOGIA · ALDENIRMED89</p><h1>Aprenda a examinar.<br>Conecte os sinais.</h1><p class="lead">Uma seção para transformar observação em raciocínio clínico. Escolha um sistema, pratique um achado e retome o que ainda merece atenção.</p></div><div class="grid"><article class="module" id="semiologia-neurologica"><img class="module-icon" src="../01_Modulos_Clinicos/Semiologia_Neurologica_Topografica/assets/icons/neuro-192.png" alt="" width="76" height="76"><span class="module-label">01 · Sistema nervoso</span><h2>Semiologia Neurológica</h2><p>Exame, topografia, atlas visual e treino do córtex ao músculo. Explore o curso completo, o exame orientado e o aplicativo de Neurologia.</p><div class="tag-row"><span class="tag">19 seções</span><span class="tag">28 casos</span><span class="tag">40 flashcards</span></div><div class="actions"><a class="button primary" href="../01_Modulos_Clinicos/Semiologia_Neurologica_Topografica/aprofundamento.html">Abrir Neurológica →</a><a class="button ghost" href="../01_Modulos_Clinicos/Semiologia_Neurologica_Topografica/index.html">Exame e visão geral</a></div><a href="../01_Modulos_Clinicos/Semiologia_Neurologica_Topografica/aprofundamento.html#instalar-app">Instalar o app de Neurologia</a></article><article class="module"><div class="heart-mark" aria-hidden="true">🫀</div><span class="module-label">02 · Coração e circulação</span><h2>Semiologia Cardiovascular</h2><p>Bulhas, sopros, atrito, pulsos, jugular e síndromes. Ouça, compare, descreva e teste suas hipóteses com casos comentados.</p><div class="tag-row"><span class="tag">30 áudios</span><span class="tag">20 casos</span><span class="tag">49 flashcards</span></div><div class="actions"><a class="button primary" href="Cardiovascular/index.html">Abrir Cardiovascular →</a><a class="button ghost" href="Cardiovascular/index.html#laboratorio">Ouvir auscultas</a></div><small>25 simulações didáticas + 5 gravações clínicas licenciadas.</small></article></div><section class="chapter-intro"><h2>Uma prática que se acumula</h2><div class="grid"><div class="panel"><h3>Escolha uma pergunta</h3><p>Um achado por vez: onde ocorre, como é produzido, o que o modifica e o que ele não permite concluir?</p></div><div class="panel"><h3>Volte à lacuna</h3><p>Use casos, comparação sonora e recuperação ativa. O progresso cardiovascular fica neste navegador e pode ser exportado para outro dispositivo.</p></div></div></section><p class="status">Conteúdo educacional para profissionais e estudantes. Módulos em revisão médica; não constituem protocolo assistencial homologado.</p><p id="offline-status" class="system-label">Preparando disponibilidade offline…</p><footer class="footer"><a href="../index.html#modulos">← Voltar às seções do site</a> · Versão 1.0 · 08/09/2026</footer></main></body></html>'''
(SECTION/'index.html').write_text(hub)
nav=[('inicio','Visão geral'),('aprender','01 · Aprender o exame'),('laboratorio','02 · Ouvir e comparar'),('focos','03 · Focos de ausculta'),('manobras-lab','04 · Manobras'),('sindromes-lab','05 · Síndromes'),('casos','06 · Casos clínicos'),('revisao','07 · Flashcards'),('checklist','08 · Prática guiada'),('progresso','09 · Meu progresso'),('fontes','Fontes e sons')]
nav_html=''.join(f'<a href="#{i}">{label}</a>' for i,label in nav)
page=head('Semiologia Cardiovascular','../../')+f'''<body>{bar('../../',True)}<div class="course-layout"><aside class="rail" id="course-nav" aria-label="Navegação do curso"><a href="../index.html">← Seção de Semiologia</a><hr>{nav_html}<hr><small>Versão 1.0 · 08/09/2026<br>Aprendizagem sem pressa.</small></aside><main class="main" id="conteudo"><section class="hero" id="inicio"><div class="hero-grid"><div><p class="eyebrow">SEMIOLOGIA / CARDIOVASCULAR</p><h1>Escute. Examine.<br>Entenda o sinal.</h1><p class="lead">O exame cardiovascular completo, do pulso ao sopro. Construa uma descrição, teste a hipótese e volte à prática com mais clareza.</p><div class="actions"><a class="button primary" href="#laboratorio">▶ Entrar no laboratório sonoro</a><a class="button ghost" id="resume-link" href="#aprender">Começar pelo exame</a></div></div><div class="orbit-card"><p class="eyebrow">SEU LABORATÓRIO DE AUSCULTA</p><div class="metrics"><div class="metric"><strong>30</strong><span>exemplos sonoros</span></div><div class="metric"><strong>20</strong><span>casos comentados</span></div><div class="metric"><strong>49</strong><span>flashcards</span></div></div><p>Ouça o normal, compare o alterado e explique a diferença antes de revelar a resposta.</p><small>25 simulações originais e 5 gravações pediátricas de fonte científica aberta.</small></div></div><p class="status">Prévia educacional em revisão médica. Sons simulados ilustram padrões; gravações reais mantêm sua origem indicada. Nenhum áudio isolado estabelece diagnóstico ou gravidade.</p><p id="offline-status" class="system-label">Preparando conteúdo e áudios offline…</p></section>
<div class="no-print"><label for="course-search" class="sr-only">Buscar no módulo</label><input class="search" id="course-search" type="search" placeholder="Buscar: B3, jugular, sopro diastólico, Valsalva…" autocomplete="off"><div id="search-results" class="search-results" aria-live="polite"></div></div>
<section class="content-section" id="aprender"><div class="section-head"><div><p class="eyebrow">01 / BASE CLÍNICA</p><h2>Um exame que faz sentido.</h2><p class="muted">Dezesseis passos, cada um com mecanismo, técnica, armadilha e uma pergunta de recuperação.</p></div><button id="expand-lessons" class="ghost no-print" type="button" aria-expanded="false">Expandir leitura</button></div>{lessons}</section>
<section class="content-section" id="laboratorio"><div class="section-head"><div><p class="eyebrow">02 / LABORATÓRIO SONORO</p><h2>Ouça o tempo. Depois o timbre.</h2><p class="muted">Escolha um exemplo, compare com outro e relacione o som a B1 e B2. Nenhum áudio inicia sozinho.</p></div></div><div class="note caution">Use fones e volume confortável. O volume digital não representa os graus de Levine. Reduzir a velocidade altera também o timbre. Gravações clínicas são clipes pediátricos curtos; não resumem toda a variabilidade da doença.</div><div class="filter-row" id="audio-filters" role="group" aria-label="Filtrar biblioteca sonora"></div><div class="audio-layout"><div><label class="sr-only" for="sound-search">Buscar som</label><input class="search" id="sound-search" placeholder="Buscar um som…" type="search"><div class="sound-catalog" id="sound-catalog" aria-label="Exemplos sonoros"></div></div><article class="panel audio-deck"><span class="audio-badge" id="sound-kind">Simulação didática</span><h3 id="sound-title">B1 e B2 · referência normal</h3><p id="sound-listen" class="muted"></p><div class="wave-shell"><canvas id="waveform" aria-label="Forma de onda do exemplo selecionado; descrição textual disponível abaixo" role="img"></canvas><div class="wave-caption" id="wave-caption">O traçado representa amplitude relativa do áudio.</div></div><audio id="audio-player" controls preload="metadata" aria-label="Reproduzir exemplo de ausculta"></audio><p id="audio-status" class="system-label" role="status"></p><div class="player-meta"><label>Velocidade <select id="audio-speed"><option value="1">1× · original</option><option value="0.75">0,75× · mais lento</option><option value="0.5">0,5× · mais lento</option></select></label><label><input id="audio-loop" type="checkbox"> Repetir</label><button id="stop-audio" class="ghost" type="button">Parar</button></div><div id="sound-details"></div><div class="comparison"><label>A · referência<select class="control-select" id="compare-a"></select><button type="button" id="play-a">Selecionar A</button></label><label>B · comparação<select class="control-select" id="compare-b"></select><button type="button" id="play-b">Selecionar B</button></label></div><small>Selecione A ou B e use o player. A seleção nunca inicia reprodução automaticamente.</small></article></div>
<div class="panel" id="treino-auditivo"><p class="eyebrow">RECUPERAÇÃO ATIVA / O RÓTULO FICA OCULTO</p><h3>Treino auditivo: qual é o padrão temporal?</h3><p>Primeiro localize B1 e B2. Depois escolha a categoria. Esta atividade reconhece exemplos didáticos; não mede desempenho diagnóstico em pacientes.</p><button class="primary" id="start-blind" type="button">Sortear um exemplo oculto</button><div id="blind-panel" hidden><p id="blind-instruction" class="note">O exemplo oculto está no player acima. Ouça antes de escolher.</p><div class="blind-options" id="blind-options"></div><div id="blind-feedback" class="feedback" hidden></div></div></div></section>
<section class="content-section" id="focos"><p class="eyebrow">03 / LOCALIZAÇÃO</p><h2>Focos são janelas acústicas.</h2><div class="grid"><div class="panel"><svg class="focus-svg" viewBox="0 0 320 370" role="img" aria-label="Esquema frontal do tórax; à esquerda da imagem está o lado direito do paciente"><path d="M113 30 Q160 62 207 30 L252 68 Q275 85 273 146 L257 341 H63 L47 146 Q45 85 68 68Z" fill="#0c2135" stroke="#496681" stroke-width="2"/><path d="M160 64V310 M91 98Q160 124 229 98 M82 131Q160 151 238 131 M76 169Q160 189 244 169 M73 207Q160 226 247 207" stroke="#2c4e67" fill="none"/><text x="57" y="30">D</text><text x="249" y="30">E</text><g data-focus="aortico" tabindex="0" role="button" aria-label="Foco aórtico" aria-pressed="true"><circle cx="140" cy="112" r="17"/><text x="140" y="117" text-anchor="middle">Ao</text></g><g data-focus="pulmonar" tabindex="0" role="button" aria-label="Foco pulmonar" aria-pressed="false"><circle cx="181" cy="112" r="17"/><text x="181" y="117" text-anchor="middle">Pu</text></g><g data-focus="erb" tabindex="0" role="button" aria-label="Foco de Erb" aria-pressed="false"><circle cx="181" cy="158" r="17"/><text x="181" y="163" text-anchor="middle">Erb</text></g><g data-focus="tricuspide" tabindex="0" role="button" aria-label="Foco tricúspide" aria-pressed="false"><circle cx="181" cy="226" r="17"/><text x="181" y="231" text-anchor="middle">Tr</text></g><g data-focus="mitral" tabindex="0" role="button" aria-label="Foco mitral" aria-pressed="false"><circle cx="224" cy="245" r="17"/><text x="224" y="250" text-anchor="middle">Mi</text></g></svg><small>Esquema didático, sem escala anatômica. Os focos não são a posição exata das válvulas.</small></div><div class="panel"><div id="focus-info" aria-live="polite"></div><div class="focus-tabs" id="focus-buttons"></div></div></div></section>
<section class="content-section" id="manobras-lab"><p class="eyebrow">04 / PREVER → OBSERVAR → EXPLICAR</p><h2>O que muda com a manobra?</h2><div class="panel"><label for="maneuver-lesion">Escolha um padrão</label><select class="control-select" id="maneuver-lesion"></select><div class="maneuver-buttons" id="maneuver-buttons"></div><div id="maneuver-result" class="note maneuver-result" aria-live="polite"></div><small>As respostas são tendências fisiológicas. O áudio da biblioteca permanece basal; este quadro não simula a resposta individual de um paciente. Manobras somente quando seguras e clinicamente apropriadas.</small></div></section>
<section class="content-section" id="sindromes-lab"><p class="eyebrow">05 / INTEGRAÇÃO</p><h2>Do conjunto de sinais à síndrome.</h2><p class="muted">Abra um padrão e compare mecanismo, próxima pergunta e armadilha.</p><div class="syndrome-grid">{syndromes}</div></section>
<section class="content-section" id="casos"><div class="section-head"><div><p class="eyebrow">06 / RACIOCÍNIO CLÍNICO</p><h2>Vinte casos. Todas as alternativas explicadas.</h2></div><button class="ghost" id="quiz-reset" type="button">Recomeçar casos</button></div><div class="panel"><div class="quiz-toolbar"><span id="quiz-position"></span><label for="case-select" class="sr-only">Escolher caso</label><select class="control-select" id="case-select"></select></div><h3 id="quiz-title"></h3><p class="quiz-stem" id="quiz-stem"></p><div class="quiz-options" id="quiz-options"></div><div id="quiz-feedback" class="quiz-feedback" aria-live="polite"></div><div class="quiz-toolbar"><button id="quiz-prev" type="button">← Anterior</button><span id="quiz-score" class="muted"></span><button id="quiz-next" class="primary" type="button">Próximo →</button></div></div></section>
<section class="content-section" id="revisao"><p class="eyebrow">07 / RETENÇÃO</p><h2>Volte ao que ainda exige esforço.</h2><div class="panel"><div class="quiz-toolbar"><span id="flash-position"></span><button id="flash-mode" class="ghost" type="button">Treinar todos</button></div><div class="flashcard"><h3 id="flash-question"></h3><div class="flash-answer" id="flash-answer" hidden></div></div><div class="flash-actions"><button id="flash-reveal" class="primary" type="button">Revelar resposta</button><button id="flash-again" type="button" disabled>Ainda difícil · voltar em breve</button><button id="flash-known" type="button" disabled>Consegui lembrar</button><button id="flash-skip" class="ghost" type="button">Pular por agora</button></div><p id="flash-status" class="system-label" role="status"></p><small>Revisões sugeridas em 1, 7, 14 e 30 dias. A fila adapta a próxima data à sua resposta; atrasos não criam dívida. Nenhum aviso externo é enviado.</small></div></section>
<section class="content-section" id="checklist"><p class="eyebrow">08 / APLICAR E RETOMAR</p><h2>Uma sequência de prática.</h2><p class="muted">Checklist de aprendizagem: marque apenas etapas estudadas ou praticadas. Não insira dados de pacientes.</p><div class="grid"><div class="panel"><h3>Exame cardiovascular</h3><div id="exam-checklist"></div><p id="checklist-count" class="system-label"></p><button id="checklist-reset" class="ghost" type="button">Limpar marcações do checklist</button></div><div><h3>Trilhas para a próxima sessão</h3><div id="study-tracks"></div><div class="note">Na prática real, confirme achados com outro examinador e com a avaliação apropriada. Este progresso registra estudo; não certifica competência clínica.</div></div></div></section>
<section class="content-section" id="progresso"><p class="eyebrow">09 / CONTINUIDADE</p><h2>Seu ponto de retomada.</h2><div id="progress-summary" class="progress-grid"></div><div class="actions"><button id="export-progress" type="button">Exportar progresso</button><label class="button import-label">Importar progresso<input type="file" id="import-progress" accept="application/json,.json" aria-label="Importar arquivo de progresso"></label><button id="print-course" class="ghost" type="button">Imprimir conteúdo</button></div><p id="announcement" role="status" aria-live="polite"></p><small>Dados locais, sem conta e sem sincronização automática. Exportação contém somente escolhas e progresso de estudo, sem prontuários. Importação válida substitui o progresso deste módulo após confirmação.</small></section>
<section class="content-section" id="fontes"><p class="eyebrow">RASTREABILIDADE / LIMITES / ATRIBUIÇÃO</p><h2>De onde vêm as explicações e os sons.</h2><div class="note">Diretrizes recentes orientam limites e avaliação clínica. Referências históricas são usadas para descrição do exame e dos fenômenos acústicos; condutas antigas, especialmente profilaxia ampla de endocardite, não são adotadas. A revisão técnica e documental não equivale a homologação médica especializada.</div><div class="source-list">{source_html}</div><h3 class="chapter-intro">Biblioteca sonora e licenças</h3><div id="audio-credits"></div><p class="muted">Simulações: síntese original por envelopes e componentes de ruído/tons para ilustrar tempo e timbre. Não foram gravadas de pacientes e não têm validação de fidelidade diagnóstica. Os WAV clínicos são os suplementos originais, sem cortes ou alterações permanentes; a velocidade opcional do player modifica apenas a reprodução.</p><a href="data/audio-manifest.json">Consultar manifesto dos áudios</a></section><footer class="footer"><a href="../index.html">← Voltar à seção de Semiologia</a> · <a href="../../index.html">Site principal</a><p>Versão educacional 1.0 · 08/09/2026 · Revisão médica especializada pendente.</p></footer><noscript><div class="note">JavaScript está desativado. A leitura clínica permanece disponível; o laboratório interativo e o progresso precisam de JavaScript.</div></noscript></main></div><script src="data/course.js"></script><script src="assets/app.js"></script></body></html>'''
(MODULE/'index.html').write_text(page)
(MODULE/'data/course.js').write_text('window.SEMIO_CARDIO = '+json.dumps(data,ensure_ascii=False,separators=(',',':'))+';\n')
manifest={'id':'semiologia-cardiovascular','title':'Semiologia Cardiovascular','version':'1.0.0','updatedAt':'2026-09-08','status':'em-revisao-medica','clinicalReviewRequired':True,'publication':{'mode':'public-preview','publicPreview':True,'clinicalReviewOngoing':True},'privacy':{'patientData':False,'progress':'localStorage','automaticSync':False},'statistics':{'lessons':len(data['lessons']),'sounds':len(data['audio']),'simulations':len(data['sounds']),'recordings':len(data['recordings']),'cases':len(data['cases']),'flashcards':len(data['flashcards']),'syndromes':len(data['syndromes'])}}
(MODULE/'module.manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n')
print(manifest['statistics'])
