#!/usr/bin/env bash
set -euo pipefail

# Cria a estrutura TEMI 2027 dentro da pasta Obsidian no iCloud.
# Ajuste OBSIDIAN_ROOT se o seu vault estiver em outro caminho.
CANDIDATES=(
  "$HOME/Library/Mobile Documents/com~apple~CloudDocs/Obsidian"
  "$HOME/Library/Mobile Documents/iCloud~md~obsidian/Documents"
  "$HOME/iCloud Drive/Obsidian"
)
OBSIDIAN_ROOT=""
for c in "${CANDIDATES[@]}"; do
  if [ -d "$c" ]; then OBSIDIAN_ROOT="$c"; break; fi
done
if [ -z "$OBSIDIAN_ROOT" ]; then
  echo 'Nao encontrei automaticamente a pasta Obsidian no iCloud.'
  read -r -p 'Cole aqui o caminho completo do seu vault/pasta Obsidian no iCloud: ' OBSIDIAN_ROOT
fi
BASE="$OBSIDIAN_ROOT/TEMI_2027"
mkdir -p "$BASE"
DIRS=(
  '00_START_AQUI'
  '01_EDITAL_E_DOCUMENTOS_OFICIAIS/2027_Edital_Quando_Publicado'
  '01_EDITAL_E_DOCUMENTOS_OFICIAIS/2026_Edital_Base'
  '01_EDITAL_E_DOCUMENTOS_OFICIAIS/Analise_Curricular'
  '01_EDITAL_E_DOCUMENTOS_OFICIAIS/Documentos_Inscricao'
  '01_EDITAL_E_DOCUMENTOS_OFICIAIS/Recursos_Espelhos'
  '02_PLANO_MESTRE_E_CRONOGRAMA/Sprints_Mensais'
  '02_PLANO_MESTRE_E_CRONOGRAMA/Metas_Semanais'
  '02_PLANO_MESTRE_E_CRONOGRAMA/Rotinas_Diarias'
  '03_FONTES_E_BIBLIOGRAFIA/00_Index_Fontes'
  '03_FONTES_E_BIBLIOGRAFIA/01_AMIB'
  '03_FONTES_E_BIBLIOGRAFIA/02_UpToDate'
  '03_FONTES_E_BIBLIOGRAFIA/03_PubMed'
  '03_FONTES_E_BIBLIOGRAFIA/04_NEJM_JAMA_BMJ_Lancet'
  '03_FONTES_E_BIBLIOGRAFIA/05_Diretrizes_Internacionais'
  '03_FONTES_E_BIBLIOGRAFIA/06_Livros_Texto'
  '03_FONTES_E_BIBLIOGRAFIA/07_Protocolos_Hospitalares'
  '03_FONTES_E_BIBLIOGRAFIA/08_Papers_Classicos'
  '03_FONTES_E_BIBLIOGRAFIA/09_Updates_Diarios'
  '05_BANCO_DE_QUESTOES_E_PROVAS/Questoes_TEMI_AMIB'
  '05_BANCO_DE_QUESTOES_E_PROVAS/Questoes_Proprias'
  '05_BANCO_DE_QUESTOES_E_PROVAS/Questoes_Por_Tema'
  '05_BANCO_DE_QUESTOES_E_PROVAS/Simulados_90Q'
  '05_BANCO_DE_QUESTOES_E_PROVAS/Provas_Anteriores_Quando_Disponiveis'
  '05_BANCO_DE_QUESTOES_E_PROVAS/Recursos_Comentados'
  '05_BANCO_DE_QUESTOES_E_PROVAS/Log_Erros'
  '06_CARDS_E_REVISAO_CONTINUA/Anki_Export'
  '06_CARDS_E_REVISAO_CONTINUA/Obsidian_Cards'
  '06_CARDS_E_REVISAO_CONTINUA/Cloze'
  '06_CARDS_E_REVISAO_CONTINUA/Revisao_24h_7d_30d_90d'
  '06_CARDS_E_REVISAO_CONTINUA/High_Yield_100'
  '06_CARDS_E_REVISAO_CONTINUA/Deck_Pratico_Estacoes'
  '07_RESUMOS_ALGORITMOS_MEMORIZADORES/Resumos_1_Pagina'
  '07_RESUMOS_ALGORITMOS_MEMORIZADORES/Algoritmos'
  '07_RESUMOS_ALGORITMOS_MEMORIZADORES/Checklists'
  '07_RESUMOS_ALGORITMOS_MEMORIZADORES/Mnemonicos'
  '07_RESUMOS_ALGORITMOS_MEMORIZADORES/Mapas_Mentais'
  '07_RESUMOS_ALGORITMOS_MEMORIZADORES/Flash_Sheets'
  '07_RESUMOS_ALGORITMOS_MEMORIZADORES/Codigos_Tabelas'
  '08_PROVA_TEORICA/Plano_Acao'
  '08_PROVA_TEORICA/Simulados'
  '08_PROVA_TEORICA/Revisao_Final'
  '08_PROVA_TEORICA/Temas_Quentes'
  '08_PROVA_TEORICA/Estrategia_Questao_Melhor_Resposta'
  '08_PROVA_TEORICA/Indice_Erros'
  '08_PROVA_TEORICA/Treino_Tempo'
  '09_PROVA_PRATICA_ESTACOES/Plano_Acao'
  '09_PROVA_PRATICA_ESTACOES/Estacoes_Simuladas'
  '09_PROVA_PRATICA_ESTACOES/Scripts_Fala'
  '09_PROVA_PRATICA_ESTACOES/Checklists_Atitudes'
  '09_PROVA_PRATICA_ESTACOES/Comunicacao_Etica'
  '09_PROVA_PRATICA_ESTACOES/Procedimentos'
  '09_PROVA_PRATICA_ESTACOES/OSCE_Rubricas'
  '09_PROVA_PRATICA_ESTACOES/Gravacoes_Treino'
  '10_ECG_VM_USG_IMAGENS/ECG'
  '10_ECG_VM_USG_IMAGENS/VM_Curvas'
  '10_ECG_VM_USG_IMAGENS/POCUS_USG_Beira_Leito'
  '10_ECG_VM_USG_IMAGENS/Radiografia_TC'
  '10_ECG_VM_USG_IMAGENS/Imagens_Destaque'
  '10_ECG_VM_USG_IMAGENS/Atlas_UTI'
  '10_ECG_VM_USG_IMAGENS/Laudos_Modelo'
  '11_ATUALIZACOES_DIARIAS_E_TEMAS_DESTAQUE/Inbox_Diaria'
  '11_ATUALIZACOES_DIARIAS_E_TEMAS_DESTAQUE/Tema_do_Dia'
  '11_ATUALIZACOES_DIARIAS_E_TEMAS_DESTAQUE/Artigo_do_Dia'
  '11_ATUALIZACOES_DIARIAS_E_TEMAS_DESTAQUE/Guideline_Watch'
  '11_ATUALIZACOES_DIARIAS_E_TEMAS_DESTAQUE/Mudancas_de_Conduta'
  '11_ATUALIZACOES_DIARIAS_E_TEMAS_DESTAQUE/Newsletter'
  '12_PONTOS_A_MELHORAR_E_METACOGNICAO/Erros_Recorrentes'
  '12_PONTOS_A_MELHORAR_E_METACOGNICAO/Lacunas'
  '12_PONTOS_A_MELHORAR_E_METACOGNICAO/Planejamento_Correcao'
  '12_PONTOS_A_MELHORAR_E_METACOGNICAO/Diario_Aprendizagem'
  '12_PONTOS_A_MELHORAR_E_METACOGNICAO/Indicadores'
  '13_DEPOSITO_DUVIDAS_PLANTAO/Duvidas_Diarias'
  '13_DEPOSITO_DUVIDAS_PLANTAO/Evolucoes_Medicas_Duvidosas'
  '13_DEPOSITO_DUVIDAS_PLANTAO/Prescricoes_Duvidosas'
  '13_DEPOSITO_DUVIDAS_PLANTAO/Condutas_Duvidosas'
  '13_DEPOSITO_DUVIDAS_PLANTAO/Farmacos_Doses'
  '13_DEPOSITO_DUVIDAS_PLANTAO/Casos_Clinicos_Reais_Anonimizados'
  '13_DEPOSITO_DUVIDAS_PLANTAO/Perguntas_para_Preceptor'
  '14_IA_ASSISTENTES/GPT'
  '14_IA_ASSISTENTES/Qwen'
  '14_IA_ASSISTENTES/Claude'
  '14_IA_ASSISTENTES/Grok'
  '14_IA_ASSISTENTES/Prompts_Padroes'
  '14_IA_ASSISTENTES/Validacao_Cruzada'
  '14_IA_ASSISTENTES/Respostas_Aprovadas'
  '14_IA_ASSISTENTES/Respostas_Rejeitadas'
  '14_IA_ASSISTENTES/Auditoria_Alucinacoes'
  '15_TEMPLATES/Markdown'
  '15_TEMPLATES/Word'
  '15_TEMPLATES/Excel'
  '15_TEMPLATES/PDF'
  '15_TEMPLATES/PNG'
  '16_EXPORTS_BACKUPS/PDF'
  '16_EXPORTS_BACKUPS/Word'
  '16_EXPORTS_BACKUPS/Excel'
  '16_EXPORTS_BACKUPS/PNG'
  '16_EXPORTS_BACKUPS/Backups_Mensais'
  '16_EXPORTS_BACKUPS/Zotero_BibTeX'
  '99_ARQUIVO_MORTO'
  '04_TEMAS_NUCLEO_TEMI/01_Fisiologia_Fisiopatologia/00_Mapa_Tema'
  '04_TEMAS_NUCLEO_TEMI/01_Fisiologia_Fisiopatologia/01_Resumos'
  '04_TEMAS_NUCLEO_TEMI/01_Fisiologia_Fisiopatologia/02_Questoes'
  '04_TEMAS_NUCLEO_TEMI/01_Fisiologia_Fisiopatologia/03_Cards'
  '04_TEMAS_NUCLEO_TEMI/01_Fisiologia_Fisiopatologia/04_Algoritmos'
  '04_TEMAS_NUCLEO_TEMI/01_Fisiologia_Fisiopatologia/05_Imagens_Destaque'
  '04_TEMAS_NUCLEO_TEMI/01_Fisiologia_Fisiopatologia/06_Provas_E_Estacoes'
  '04_TEMAS_NUCLEO_TEMI/01_Fisiologia_Fisiopatologia/07_Erros_Pontos_Melhorar'
  '04_TEMAS_NUCLEO_TEMI/01_Fisiologia_Fisiopatologia/08_Fontes'
  '04_TEMAS_NUCLEO_TEMI/01_Fisiologia_Fisiopatologia/09_Revisoes'
  '04_TEMAS_NUCLEO_TEMI/02_Hemodinamica_Choque/00_Mapa_Tema'
  '04_TEMAS_NUCLEO_TEMI/02_Hemodinamica_Choque/01_Resumos'
  '04_TEMAS_NUCLEO_TEMI/02_Hemodinamica_Choque/02_Questoes'
  '04_TEMAS_NUCLEO_TEMI/02_Hemodinamica_Choque/03_Cards'
  '04_TEMAS_NUCLEO_TEMI/02_Hemodinamica_Choque/04_Algoritmos'
  '04_TEMAS_NUCLEO_TEMI/02_Hemodinamica_Choque/05_Imagens_Destaque'
  '04_TEMAS_NUCLEO_TEMI/02_Hemodinamica_Choque/06_Provas_E_Estacoes'
  '04_TEMAS_NUCLEO_TEMI/02_Hemodinamica_Choque/07_Erros_Pontos_Melhorar'
  '04_TEMAS_NUCLEO_TEMI/02_Hemodinamica_Choque/08_Fontes'
  '04_TEMAS_NUCLEO_TEMI/02_Hemodinamica_Choque/09_Revisoes'
  '04_TEMAS_NUCLEO_TEMI/03_Respiratorio_VM/00_Mapa_Tema'
  '04_TEMAS_NUCLEO_TEMI/03_Respiratorio_VM/01_Resumos'
  '04_TEMAS_NUCLEO_TEMI/03_Respiratorio_VM/02_Questoes'
  '04_TEMAS_NUCLEO_TEMI/03_Respiratorio_VM/03_Cards'
  '04_TEMAS_NUCLEO_TEMI/03_Respiratorio_VM/04_Algoritmos'
  '04_TEMAS_NUCLEO_TEMI/03_Respiratorio_VM/05_Imagens_Destaque'
  '04_TEMAS_NUCLEO_TEMI/03_Respiratorio_VM/06_Provas_E_Estacoes'
  '04_TEMAS_NUCLEO_TEMI/03_Respiratorio_VM/07_Erros_Pontos_Melhorar'
  '04_TEMAS_NUCLEO_TEMI/03_Respiratorio_VM/08_Fontes'
  '04_TEMAS_NUCLEO_TEMI/03_Respiratorio_VM/09_Revisoes'
  '04_TEMAS_NUCLEO_TEMI/04_Sepse_Infeccoes_Antimicrobianos/00_Mapa_Tema'
  '04_TEMAS_NUCLEO_TEMI/04_Sepse_Infeccoes_Antimicrobianos/01_Resumos'
  '04_TEMAS_NUCLEO_TEMI/04_Sepse_Infeccoes_Antimicrobianos/02_Questoes'
  '04_TEMAS_NUCLEO_TEMI/04_Sepse_Infeccoes_Antimicrobianos/03_Cards'
  '04_TEMAS_NUCLEO_TEMI/04_Sepse_Infeccoes_Antimicrobianos/04_Algoritmos'
  '04_TEMAS_NUCLEO_TEMI/04_Sepse_Infeccoes_Antimicrobianos/05_Imagens_Destaque'
  '04_TEMAS_NUCLEO_TEMI/04_Sepse_Infeccoes_Antimicrobianos/06_Provas_E_Estacoes'
  '04_TEMAS_NUCLEO_TEMI/04_Sepse_Infeccoes_Antimicrobianos/07_Erros_Pontos_Melhorar'
  '04_TEMAS_NUCLEO_TEMI/04_Sepse_Infeccoes_Antimicrobianos/08_Fontes'
  '04_TEMAS_NUCLEO_TEMI/04_Sepse_Infeccoes_Antimicrobianos/09_Revisoes'
  '04_TEMAS_NUCLEO_TEMI/05_Renal_TSR/00_Mapa_Tema'
  '04_TEMAS_NUCLEO_TEMI/05_Renal_TSR/01_Resumos'
  '04_TEMAS_NUCLEO_TEMI/05_Renal_TSR/02_Questoes'
  '04_TEMAS_NUCLEO_TEMI/05_Renal_TSR/03_Cards'
  '04_TEMAS_NUCLEO_TEMI/05_Renal_TSR/04_Algoritmos'
  '04_TEMAS_NUCLEO_TEMI/05_Renal_TSR/05_Imagens_Destaque'
  '04_TEMAS_NUCLEO_TEMI/05_Renal_TSR/06_Provas_E_Estacoes'
  '04_TEMAS_NUCLEO_TEMI/05_Renal_TSR/07_Erros_Pontos_Melhorar'
  '04_TEMAS_NUCLEO_TEMI/05_Renal_TSR/08_Fontes'
  '04_TEMAS_NUCLEO_TEMI/05_Renal_TSR/09_Revisoes'
  '04_TEMAS_NUCLEO_TEMI/06_Cardiovascular_SCA_TEP/00_Mapa_Tema'
  '04_TEMAS_NUCLEO_TEMI/06_Cardiovascular_SCA_TEP/01_Resumos'
  '04_TEMAS_NUCLEO_TEMI/06_Cardiovascular_SCA_TEP/02_Questoes'
  '04_TEMAS_NUCLEO_TEMI/06_Cardiovascular_SCA_TEP/03_Cards'
  '04_TEMAS_NUCLEO_TEMI/06_Cardiovascular_SCA_TEP/04_Algoritmos'
  '04_TEMAS_NUCLEO_TEMI/06_Cardiovascular_SCA_TEP/05_Imagens_Destaque'
  '04_TEMAS_NUCLEO_TEMI/06_Cardiovascular_SCA_TEP/06_Provas_E_Estacoes'
  '04_TEMAS_NUCLEO_TEMI/06_Cardiovascular_SCA_TEP/07_Erros_Pontos_Melhorar'
  '04_TEMAS_NUCLEO_TEMI/06_Cardiovascular_SCA_TEP/08_Fontes'
  '04_TEMAS_NUCLEO_TEMI/06_Cardiovascular_SCA_TEP/09_Revisoes'
  '04_TEMAS_NUCLEO_TEMI/07_Neurointensivismo/00_Mapa_Tema'
  '04_TEMAS_NUCLEO_TEMI/07_Neurointensivismo/01_Resumos'
  '04_TEMAS_NUCLEO_TEMI/07_Neurointensivismo/02_Questoes'
  '04_TEMAS_NUCLEO_TEMI/07_Neurointensivismo/03_Cards'
  '04_TEMAS_NUCLEO_TEMI/07_Neurointensivismo/04_Algoritmos'
  '04_TEMAS_NUCLEO_TEMI/07_Neurointensivismo/05_Imagens_Destaque'
  '04_TEMAS_NUCLEO_TEMI/07_Neurointensivismo/06_Provas_E_Estacoes'
  '04_TEMAS_NUCLEO_TEMI/07_Neurointensivismo/07_Erros_Pontos_Melhorar'
  '04_TEMAS_NUCLEO_TEMI/07_Neurointensivismo/08_Fontes'
  '04_TEMAS_NUCLEO_TEMI/07_Neurointensivismo/09_Revisoes'
  '04_TEMAS_NUCLEO_TEMI/08_Gastro_Hepatico_Nutricao/00_Mapa_Tema'
  '04_TEMAS_NUCLEO_TEMI/08_Gastro_Hepatico_Nutricao/01_Resumos'
  '04_TEMAS_NUCLEO_TEMI/08_Gastro_Hepatico_Nutricao/02_Questoes'
  '04_TEMAS_NUCLEO_TEMI/08_Gastro_Hepatico_Nutricao/03_Cards'
  '04_TEMAS_NUCLEO_TEMI/08_Gastro_Hepatico_Nutricao/04_Algoritmos'
  '04_TEMAS_NUCLEO_TEMI/08_Gastro_Hepatico_Nutricao/05_Imagens_Destaque'
  '04_TEMAS_NUCLEO_TEMI/08_Gastro_Hepatico_Nutricao/06_Provas_E_Estacoes'
  '04_TEMAS_NUCLEO_TEMI/08_Gastro_Hepatico_Nutricao/07_Erros_Pontos_Melhorar'
  '04_TEMAS_NUCLEO_TEMI/08_Gastro_Hepatico_Nutricao/08_Fontes'
  '04_TEMAS_NUCLEO_TEMI/08_Gastro_Hepatico_Nutricao/09_Revisoes'
  '04_TEMAS_NUCLEO_TEMI/09_Hematologia_Coagulacao_Hemorragia/00_Mapa_Tema'
  '04_TEMAS_NUCLEO_TEMI/09_Hematologia_Coagulacao_Hemorragia/01_Resumos'
  '04_TEMAS_NUCLEO_TEMI/09_Hematologia_Coagulacao_Hemorragia/02_Questoes'
  '04_TEMAS_NUCLEO_TEMI/09_Hematologia_Coagulacao_Hemorragia/03_Cards'
  '04_TEMAS_NUCLEO_TEMI/09_Hematologia_Coagulacao_Hemorragia/04_Algoritmos'
  '04_TEMAS_NUCLEO_TEMI/09_Hematologia_Coagulacao_Hemorragia/05_Imagens_Destaque'
  '04_TEMAS_NUCLEO_TEMI/09_Hematologia_Coagulacao_Hemorragia/06_Provas_E_Estacoes'
  '04_TEMAS_NUCLEO_TEMI/09_Hematologia_Coagulacao_Hemorragia/07_Erros_Pontos_Melhorar'
  '04_TEMAS_NUCLEO_TEMI/09_Hematologia_Coagulacao_Hemorragia/08_Fontes'
  '04_TEMAS_NUCLEO_TEMI/09_Hematologia_Coagulacao_Hemorragia/09_Revisoes'
  '04_TEMAS_NUCLEO_TEMI/10_Endocrino_Metabolico_AcidoBase/00_Mapa_Tema'
  '04_TEMAS_NUCLEO_TEMI/10_Endocrino_Metabolico_AcidoBase/01_Resumos'
  '04_TEMAS_NUCLEO_TEMI/10_Endocrino_Metabolico_AcidoBase/02_Questoes'
  '04_TEMAS_NUCLEO_TEMI/10_Endocrino_Metabolico_AcidoBase/03_Cards'
  '04_TEMAS_NUCLEO_TEMI/10_Endocrino_Metabolico_AcidoBase/04_Algoritmos'
  '04_TEMAS_NUCLEO_TEMI/10_Endocrino_Metabolico_AcidoBase/05_Imagens_Destaque'
  '04_TEMAS_NUCLEO_TEMI/10_Endocrino_Metabolico_AcidoBase/06_Provas_E_Estacoes'
  '04_TEMAS_NUCLEO_TEMI/10_Endocrino_Metabolico_AcidoBase/07_Erros_Pontos_Melhorar'
  '04_TEMAS_NUCLEO_TEMI/10_Endocrino_Metabolico_AcidoBase/08_Fontes'
  '04_TEMAS_NUCLEO_TEMI/10_Endocrino_Metabolico_AcidoBase/09_Revisoes'
  '04_TEMAS_NUCLEO_TEMI/11_Trauma_Queimados_Toxicologia/00_Mapa_Tema'
  '04_TEMAS_NUCLEO_TEMI/11_Trauma_Queimados_Toxicologia/01_Resumos'
  '04_TEMAS_NUCLEO_TEMI/11_Trauma_Queimados_Toxicologia/02_Questoes'
  '04_TEMAS_NUCLEO_TEMI/11_Trauma_Queimados_Toxicologia/03_Cards'
  '04_TEMAS_NUCLEO_TEMI/11_Trauma_Queimados_Toxicologia/04_Algoritmos'
  '04_TEMAS_NUCLEO_TEMI/11_Trauma_Queimados_Toxicologia/05_Imagens_Destaque'
  '04_TEMAS_NUCLEO_TEMI/11_Trauma_Queimados_Toxicologia/06_Provas_E_Estacoes'
  '04_TEMAS_NUCLEO_TEMI/11_Trauma_Queimados_Toxicologia/07_Erros_Pontos_Melhorar'
  '04_TEMAS_NUCLEO_TEMI/11_Trauma_Queimados_Toxicologia/08_Fontes'
  '04_TEMAS_NUCLEO_TEMI/11_Trauma_Queimados_Toxicologia/09_Revisoes'
  '04_TEMAS_NUCLEO_TEMI/12_Perioperatorio_Paciente_Cirurgico/00_Mapa_Tema'
  '04_TEMAS_NUCLEO_TEMI/12_Perioperatorio_Paciente_Cirurgico/01_Resumos'
  '04_TEMAS_NUCLEO_TEMI/12_Perioperatorio_Paciente_Cirurgico/02_Questoes'
  '04_TEMAS_NUCLEO_TEMI/12_Perioperatorio_Paciente_Cirurgico/03_Cards'
  '04_TEMAS_NUCLEO_TEMI/12_Perioperatorio_Paciente_Cirurgico/04_Algoritmos'
  '04_TEMAS_NUCLEO_TEMI/12_Perioperatorio_Paciente_Cirurgico/05_Imagens_Destaque'
  '04_TEMAS_NUCLEO_TEMI/12_Perioperatorio_Paciente_Cirurgico/06_Provas_E_Estacoes'
  '04_TEMAS_NUCLEO_TEMI/12_Perioperatorio_Paciente_Cirurgico/07_Erros_Pontos_Melhorar'
  '04_TEMAS_NUCLEO_TEMI/12_Perioperatorio_Paciente_Cirurgico/08_Fontes'
  '04_TEMAS_NUCLEO_TEMI/12_Perioperatorio_Paciente_Cirurgico/09_Revisoes'
  '04_TEMAS_NUCLEO_TEMI/13_Sedacao_Analgesia_Delirium_Mobilizacao/00_Mapa_Tema'
  '04_TEMAS_NUCLEO_TEMI/13_Sedacao_Analgesia_Delirium_Mobilizacao/01_Resumos'
  '04_TEMAS_NUCLEO_TEMI/13_Sedacao_Analgesia_Delirium_Mobilizacao/02_Questoes'
  '04_TEMAS_NUCLEO_TEMI/13_Sedacao_Analgesia_Delirium_Mobilizacao/03_Cards'
  '04_TEMAS_NUCLEO_TEMI/13_Sedacao_Analgesia_Delirium_Mobilizacao/04_Algoritmos'
  '04_TEMAS_NUCLEO_TEMI/13_Sedacao_Analgesia_Delirium_Mobilizacao/05_Imagens_Destaque'
  '04_TEMAS_NUCLEO_TEMI/13_Sedacao_Analgesia_Delirium_Mobilizacao/06_Provas_E_Estacoes'
  '04_TEMAS_NUCLEO_TEMI/13_Sedacao_Analgesia_Delirium_Mobilizacao/07_Erros_Pontos_Melhorar'
  '04_TEMAS_NUCLEO_TEMI/13_Sedacao_Analgesia_Delirium_Mobilizacao/08_Fontes'
  '04_TEMAS_NUCLEO_TEMI/13_Sedacao_Analgesia_Delirium_Mobilizacao/09_Revisoes'
  '04_TEMAS_NUCLEO_TEMI/14_Cuidados_Paliativos_Etica_Comunicacao/00_Mapa_Tema'
  '04_TEMAS_NUCLEO_TEMI/14_Cuidados_Paliativos_Etica_Comunicacao/01_Resumos'
  '04_TEMAS_NUCLEO_TEMI/14_Cuidados_Paliativos_Etica_Comunicacao/02_Questoes'
  '04_TEMAS_NUCLEO_TEMI/14_Cuidados_Paliativos_Etica_Comunicacao/03_Cards'
  '04_TEMAS_NUCLEO_TEMI/14_Cuidados_Paliativos_Etica_Comunicacao/04_Algoritmos'
  '04_TEMAS_NUCLEO_TEMI/14_Cuidados_Paliativos_Etica_Comunicacao/05_Imagens_Destaque'
  '04_TEMAS_NUCLEO_TEMI/14_Cuidados_Paliativos_Etica_Comunicacao/06_Provas_E_Estacoes'
  '04_TEMAS_NUCLEO_TEMI/14_Cuidados_Paliativos_Etica_Comunicacao/07_Erros_Pontos_Melhorar'
  '04_TEMAS_NUCLEO_TEMI/14_Cuidados_Paliativos_Etica_Comunicacao/08_Fontes'
  '04_TEMAS_NUCLEO_TEMI/14_Cuidados_Paliativos_Etica_Comunicacao/09_Revisoes'
  '04_TEMAS_NUCLEO_TEMI/15_Gestao_Qualidade_Seguranca/00_Mapa_Tema'
  '04_TEMAS_NUCLEO_TEMI/15_Gestao_Qualidade_Seguranca/01_Resumos'
  '04_TEMAS_NUCLEO_TEMI/15_Gestao_Qualidade_Seguranca/02_Questoes'
  '04_TEMAS_NUCLEO_TEMI/15_Gestao_Qualidade_Seguranca/03_Cards'
  '04_TEMAS_NUCLEO_TEMI/15_Gestao_Qualidade_Seguranca/04_Algoritmos'
  '04_TEMAS_NUCLEO_TEMI/15_Gestao_Qualidade_Seguranca/05_Imagens_Destaque'
  '04_TEMAS_NUCLEO_TEMI/15_Gestao_Qualidade_Seguranca/06_Provas_E_Estacoes'
  '04_TEMAS_NUCLEO_TEMI/15_Gestao_Qualidade_Seguranca/07_Erros_Pontos_Melhorar'
  '04_TEMAS_NUCLEO_TEMI/15_Gestao_Qualidade_Seguranca/08_Fontes'
  '04_TEMAS_NUCLEO_TEMI/15_Gestao_Qualidade_Seguranca/09_Revisoes'
  '04_TEMAS_NUCLEO_TEMI/16_Metodologia_Cientifica_Bioestatistica/00_Mapa_Tema'
  '04_TEMAS_NUCLEO_TEMI/16_Metodologia_Cientifica_Bioestatistica/01_Resumos'
  '04_TEMAS_NUCLEO_TEMI/16_Metodologia_Cientifica_Bioestatistica/02_Questoes'
  '04_TEMAS_NUCLEO_TEMI/16_Metodologia_Cientifica_Bioestatistica/03_Cards'
  '04_TEMAS_NUCLEO_TEMI/16_Metodologia_Cientifica_Bioestatistica/04_Algoritmos'
  '04_TEMAS_NUCLEO_TEMI/16_Metodologia_Cientifica_Bioestatistica/05_Imagens_Destaque'
  '04_TEMAS_NUCLEO_TEMI/16_Metodologia_Cientifica_Bioestatistica/06_Provas_E_Estacoes'
  '04_TEMAS_NUCLEO_TEMI/16_Metodologia_Cientifica_Bioestatistica/07_Erros_Pontos_Melhorar'
  '04_TEMAS_NUCLEO_TEMI/16_Metodologia_Cientifica_Bioestatistica/08_Fontes'
  '04_TEMAS_NUCLEO_TEMI/16_Metodologia_Cientifica_Bioestatistica/09_Revisoes'
  '04_TEMAS_NUCLEO_TEMI/17_ECG_e_Arritmias/00_Mapa_Tema'
  '04_TEMAS_NUCLEO_TEMI/17_ECG_e_Arritmias/01_Resumos'
  '04_TEMAS_NUCLEO_TEMI/17_ECG_e_Arritmias/02_Questoes'
  '04_TEMAS_NUCLEO_TEMI/17_ECG_e_Arritmias/03_Cards'
  '04_TEMAS_NUCLEO_TEMI/17_ECG_e_Arritmias/04_Algoritmos'
  '04_TEMAS_NUCLEO_TEMI/17_ECG_e_Arritmias/05_Imagens_Destaque'
  '04_TEMAS_NUCLEO_TEMI/17_ECG_e_Arritmias/06_Provas_E_Estacoes'
  '04_TEMAS_NUCLEO_TEMI/17_ECG_e_Arritmias/07_Erros_Pontos_Melhorar'
  '04_TEMAS_NUCLEO_TEMI/17_ECG_e_Arritmias/08_Fontes'
  '04_TEMAS_NUCLEO_TEMI/17_ECG_e_Arritmias/09_Revisoes'
  '04_TEMAS_NUCLEO_TEMI/18_POCUS_USG_Beira_Leito/00_Mapa_Tema'
  '04_TEMAS_NUCLEO_TEMI/18_POCUS_USG_Beira_Leito/01_Resumos'
  '04_TEMAS_NUCLEO_TEMI/18_POCUS_USG_Beira_Leito/02_Questoes'
  '04_TEMAS_NUCLEO_TEMI/18_POCUS_USG_Beira_Leito/03_Cards'
  '04_TEMAS_NUCLEO_TEMI/18_POCUS_USG_Beira_Leito/04_Algoritmos'
  '04_TEMAS_NUCLEO_TEMI/18_POCUS_USG_Beira_Leito/05_Imagens_Destaque'
  '04_TEMAS_NUCLEO_TEMI/18_POCUS_USG_Beira_Leito/06_Provas_E_Estacoes'
  '04_TEMAS_NUCLEO_TEMI/18_POCUS_USG_Beira_Leito/07_Erros_Pontos_Melhorar'
  '04_TEMAS_NUCLEO_TEMI/18_POCUS_USG_Beira_Leito/08_Fontes'
  '04_TEMAS_NUCLEO_TEMI/18_POCUS_USG_Beira_Leito/09_Revisoes'
  '04_TEMAS_NUCLEO_TEMI/19_Procedimentos_UCI/00_Mapa_Tema'
  '04_TEMAS_NUCLEO_TEMI/19_Procedimentos_UCI/01_Resumos'
  '04_TEMAS_NUCLEO_TEMI/19_Procedimentos_UCI/02_Questoes'
  '04_TEMAS_NUCLEO_TEMI/19_Procedimentos_UCI/03_Cards'
  '04_TEMAS_NUCLEO_TEMI/19_Procedimentos_UCI/04_Algoritmos'
  '04_TEMAS_NUCLEO_TEMI/19_Procedimentos_UCI/05_Imagens_Destaque'
  '04_TEMAS_NUCLEO_TEMI/19_Procedimentos_UCI/06_Provas_E_Estacoes'
  '04_TEMAS_NUCLEO_TEMI/19_Procedimentos_UCI/07_Erros_Pontos_Melhorar'
  '04_TEMAS_NUCLEO_TEMI/19_Procedimentos_UCI/08_Fontes'
  '04_TEMAS_NUCLEO_TEMI/19_Procedimentos_UCI/09_Revisoes'
  '04_TEMAS_NUCLEO_TEMI/20_Farmacologia_UCI/00_Mapa_Tema'
  '04_TEMAS_NUCLEO_TEMI/20_Farmacologia_UCI/01_Resumos'
  '04_TEMAS_NUCLEO_TEMI/20_Farmacologia_UCI/02_Questoes'
  '04_TEMAS_NUCLEO_TEMI/20_Farmacologia_UCI/03_Cards'
  '04_TEMAS_NUCLEO_TEMI/20_Farmacologia_UCI/04_Algoritmos'
  '04_TEMAS_NUCLEO_TEMI/20_Farmacologia_UCI/05_Imagens_Destaque'
  '04_TEMAS_NUCLEO_TEMI/20_Farmacologia_UCI/06_Provas_E_Estacoes'
  '04_TEMAS_NUCLEO_TEMI/20_Farmacologia_UCI/07_Erros_Pontos_Melhorar'
  '04_TEMAS_NUCLEO_TEMI/20_Farmacologia_UCI/08_Fontes'
  '04_TEMAS_NUCLEO_TEMI/20_Farmacologia_UCI/09_Revisoes'
  '04_TEMAS_NUCLEO_TEMI/21_Obstetricia_Critica/00_Mapa_Tema'
  '04_TEMAS_NUCLEO_TEMI/21_Obstetricia_Critica/01_Resumos'
  '04_TEMAS_NUCLEO_TEMI/21_Obstetricia_Critica/02_Questoes'
  '04_TEMAS_NUCLEO_TEMI/21_Obstetricia_Critica/03_Cards'
  '04_TEMAS_NUCLEO_TEMI/21_Obstetricia_Critica/04_Algoritmos'
  '04_TEMAS_NUCLEO_TEMI/21_Obstetricia_Critica/05_Imagens_Destaque'
  '04_TEMAS_NUCLEO_TEMI/21_Obstetricia_Critica/06_Provas_E_Estacoes'
  '04_TEMAS_NUCLEO_TEMI/21_Obstetricia_Critica/07_Erros_Pontos_Melhorar'
  '04_TEMAS_NUCLEO_TEMI/21_Obstetricia_Critica/08_Fontes'
  '04_TEMAS_NUCLEO_TEMI/21_Obstetricia_Critica/09_Revisoes'
  '04_TEMAS_NUCLEO_TEMI/22_Imagem_Radiologia_Critica/00_Mapa_Tema'
  '04_TEMAS_NUCLEO_TEMI/22_Imagem_Radiologia_Critica/01_Resumos'
  '04_TEMAS_NUCLEO_TEMI/22_Imagem_Radiologia_Critica/02_Questoes'
  '04_TEMAS_NUCLEO_TEMI/22_Imagem_Radiologia_Critica/03_Cards'
  '04_TEMAS_NUCLEO_TEMI/22_Imagem_Radiologia_Critica/04_Algoritmos'
  '04_TEMAS_NUCLEO_TEMI/22_Imagem_Radiologia_Critica/05_Imagens_Destaque'
  '04_TEMAS_NUCLEO_TEMI/22_Imagem_Radiologia_Critica/06_Provas_E_Estacoes'
  '04_TEMAS_NUCLEO_TEMI/22_Imagem_Radiologia_Critica/07_Erros_Pontos_Melhorar'
  '04_TEMAS_NUCLEO_TEMI/22_Imagem_Radiologia_Critica/08_Fontes'
  '04_TEMAS_NUCLEO_TEMI/22_Imagem_Radiologia_Critica/09_Revisoes'
)
for d in "${DIRS[@]}"; do
  mkdir -p "$BASE/$d"
done
cat > "$BASE/README_TEMI_2027.md" <<'EOF'
# TEMI 2027 - Central de Preparação

Este vault foi desenhado para funcionar como um sistema vivo de estudo para o TEMI 2027: leitura, questões, resumos, cards, algoritmos, prova prática, atualizações, dúvidas de plantão e auditoria de respostas por IA.

## Fluxo mínimo diário

1. Capturar: dúvida, questão errada, imagem, ECG, curva de VM ou conduta que gerou insegurança.
2. Classificar: tema, fonte, nível de urgência e pasta correta.
3. Transformar: resumo de 1 página, card ou algoritmo.
4. Testar: questões, caso oral ou estação prática.
5. Revisar: 24 h, 7 d, 30 d, 90 d.
6. Consolidar: mover para `Respostas_Aprovadas`, `Algoritmos` ou `High_Yield_100`.

## Regra de ouro

Nenhum conteúdo entra no acervo definitivo sem fonte, data, tema, síntese e próxima revisão.
EOF
cat > "$BASE/00_START_AQUI/Guia_Rapido_Rotina_Diaria.md" <<'EOF'
# Rotina diária adaptativa TEMI 2027

## Dia de 15 minutos - modo sobrevivência
- 5 min: revisar 10 cards vencidos.
- 5 min: reler 1 erro antigo e escrever a conduta correta.
- 5 min: desenhar de cabeça 1 algoritmo ou responder 1 mini-caso oral.

## Dia de 30 minutos - modo manutenção
- 10 min: 8 a 12 questões rápidas.
- 10 min: comentar erros sem olhar o gabarito inicialmente.
- 10 min: criar 3 cards de alto rendimento.

## Dia de 60 minutos - modo padrão
- 15 min: revisão espaçada.
- 25 min: estudo ativo de tema da semana.
- 15 min: questões do mesmo tema.
- 5 min: atualizar dashboard e pontos a melhorar.

## Dia de 90 a 120 minutos - modo avanço
- 25 min: leitura de fonte principal.
- 25 min: questões/casos.
- 20 min: resumo visual ou algoritmo.
- 15 min: cards e revisão.
- 10 min: simulação oral/prática.

## Dia pós-plantão
A meta não é produtividade máxima: é continuidade. Fazer apenas o ciclo de 15 minutos já mantém o sistema vivo.
EOF
echo ''
echo 'Estrutura TEMI 2027 criada em:'
echo "$BASE"
echo 'Agora abra esta pasta como vault ou subpasta no Obsidian.'
